In [1]:
import numpy as np

#### Random module

In [5]:
## Get random value between 0 to 1
np.random.random()

0.8720623444707388

Everytime we run above we get different value each time.

In [9]:
np.random.seed(12)
np.random.random()

0.15416284237967237

If we want to fix the random number then we can use seed. Even if we run above multiple times we get same number.

In [12]:
### Get random floating number within given range.
## Everytime we run the cell we get different output.
np.random.uniform(3,10)

6.736175753662084

In [14]:
### Get 10 random floating number within given range.
## Everytime we run the cell we get different output.
np.random.uniform(3,100,10)

array([ 3.21914565, 53.55892464, 56.54765043, 50.08160913, 77.50901294,
       18.58952505, 77.16236368,  5.0185504 , 16.1153873 , 14.27848269])

In [17]:
### Get random integer number within given range.
np.random.randint(1,100)

54

In [18]:
### Get 5 random integer number within given range.
np.random.randint(1,100,5)

array([48, 61, 97, 43, 71])

If we want to generate a 2D array, then we can use same function as above and reshape it.

In [19]:
np.random.randint(1,100,10).reshape(5,2)

array([[71, 68],
       [ 3, 29],
       [75, 59],
       [60, 85],
       [55, 56]])

In [25]:
## Get maximum element in array
a=np.random.randint(1,10,6)
print(a)
print(a.max())
print(np.max(a))
print(a.min())
print(np.min(a))

[1 1 6 5 1 4]
6
6
1
1


In [28]:
## argmax will give index of maximum element
## argmin will give index of minimum element
print(a)
print(np.argmax(a))
print(a.argmax())
print(np.argmin(a))
print(a.argmin())

[1 1 6 5 1 4]
2
2
0
0


In [30]:
## Replace all the odd elements with -1
mask=a%2!=0
a[mask]=-1
print(a)

[-1 -1  6 -1 -1  4]


Here the original array got modified, but when we dont want to change original array then we can use where function.

In [31]:
a=np.random.randint(1,50,10)
print(a)

[46 24 39 48 34  5 26 45 23  6]


In [32]:
print(np.where(a%2!=0,-1,a))
print(a)

[46 24 -1 48 34 -1 26 -1 -1  6]
[46 24 39 48 34  5 26 45 23  6]


Now the original array is unchanged. Where returns the another array and wont modify the original one.

In [35]:
## Sort the array
a=np.sort(a)
a 

array([ 5,  6, 23, 24, 26, 34, 39, 45, 46, 48])

In [36]:
## 25 th Percentile will lie between 23 and 24
np.percentile(a,25)

23.25

In [37]:
## This will make sure half of the elements of array are less than the 50th percentile value.
np.percentile(a,50)

30.0

In [39]:
np.percentile(a,100)

48.0